// Собраны все файлы, для работы в main
#include "variables.hpp"
#include "console.hpp"
#include "cycles.hpp"
#include "control_structures.hpp"
#include "rest.hpp"
#include "string.hpp"
#include "struct.hpp"
#include "pointer.hpp"
#include "array.hpp"
#include "function.hpp"
#include "escape.hpp"
#include "rand.hpp"